name: Remote Test on Google Cloud

on: [push]

jobs:
  laravel-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          cd src
          composer install --no-interaction --prefer-dist --optimize-autoloader
          
          cp .env.example .env
          echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          echo "VITE_SKIP_PRECOGNITION=true" >> .env
          
          php artisan test