name: Remote Test on Google Cloud

on: [push]

jobs:
  laravel-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          cd src
          composer install --no-interaction --prefer-dist --optimize-autoloader
          
          if [ ! -f .env ]; then
            cp .env.testing .env
          fi
          
          php artisan test